name: 'Update conda CI via /rerender PR comment'
on:
  issue_comment:
    types: [created, edited]
jobs:
  rerender:
    name: Re-render conda CI
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/rerender') }}
    steps:
      - uses: actions/github-script@v5
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.rest.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
      - name: install conda-smithy
        uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: |
            conda-smithy
      - name: rerender
        shell: bash -l {0}
        run: |
          conda smithy rerender --feedstock_config .conda-forge.yml
      - name: commit and push
        uses: EndBug/add-and-commit@v7
        with:
          message: 'CI: Re-rendered conda CI scripts via Github Action'
          remove: '.github/workflows/automerge.yml .github/workflows/webservices.yml .circleci/config.yml'
          signoff: true
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            })
